/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.customer;

import com.parkhomenko.customer.Customer;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "CUSTOMER_GROUP")
public class CustomerGroup {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @Basic
    private String shortDescription;

    @OneToMany(targetEntity = Customer.class)
    @JoinColumn(name = "CUSTOMERGROUP_ID")
    private List<Customer> customers;

    public void addCustomer(Customer customer) {
        getCustomers().add(customer);
    }

    public void removeCustomer(Customer customer) {
        getCustomers().remove(customer);
    }

}