/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.customer;

import com.parkhomenko.customer.Customer;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author dmytro
 */
@Entity
@Table(name = "CUSTOMER_GROUP")
public class CustomerGroup {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @Basic
    private String shortDescription;

    @OneToMany(targetEntity = Customer.class)
    @JoinColumn(name = "CUSTOMERGROUP_ID")
    private List<Customer> customers;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShortDescription() {
        return this.shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public List<Customer> getCustomers() {
        if (customers == null) {
            customers = new ArrayList<>();
        }
        return this.customers;
    }

    public void setCustomers(List<Customer> customers) {
        this.customers = customers;
    }

    public void addCustomer(Customer customer) {
        getCustomers().add(customer);
    }

    public void removeCustomer(Customer customer) {
        getCustomers().remove(customer);
    }

}