/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.customer;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "SESSION_TABLE")
public class Session {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String ipAddress;

    @Basic
    private String token;

    @Basic
    private String startDate;

    @Basic
    private String endDate;
}