/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author dmytro
 */
@Entity
@Table(name = "PRODUCT_PROPERTY")
public class ProductProperty {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false)
    @Basic
    @NotNull
    private String type;

    @Basic
    private String validation_regexp;

    @Basic
    private String validation_length_min;

    @Basic
    private String validation_length_max;

    @Basic
    private String name;

    @Basic
    private String shortDescription;

    @OneToMany(targetEntity = PropertyStaticValue.class)
    @JoinColumn(name = "PRODUCT_PROPERTY_ID")
    private List<PropertyStaticValue> property_static_values;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getValidation_regexp() {
        return this.validation_regexp;
    }

    public void setValidation_regexp(String validation_regexp) {
        this.validation_regexp = validation_regexp;
    }

    public String getValidation_length_min() {
        return this.validation_length_min;
    }

    public void setValidation_length_min(String validation_length_min) {
        this.validation_length_min = validation_length_min;
    }

    public String getValidation_length_max() {
        return this.validation_length_max;
    }

    public void setValidation_length_max(String validation_length_max) {
        this.validation_length_max = validation_length_max;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShortDescription() {
        return this.shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public List<PropertyStaticValue> getProperty_static_values() {
        if (property_static_values == null) {
            property_static_values = new ArrayList<>();
        }
        return this.property_static_values;
    }

    public void setProperty_static_values(List<PropertyStaticValue> property_static_values) {
        this.property_static_values = property_static_values;
    }

    public void addProperty_static_value(PropertyStaticValue property_static_value) {
        getProperty_static_values().add(property_static_value);
    }

    public void removeProperty_static_value(PropertyStaticValue property_static_value) {
        getProperty_static_values().remove(property_static_value);
    }

}