/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * @author dmytro
 */
@Entity
@Table(name = "TRANSLATION_PRODUCT")
public class TranslationProduct implements Serializable {

    @Basic
    private String name;

    @Basic
    private String description;

    @Id
    @OneToOne(targetEntity = Product.class)
    private Product product;

    @ManyToOne(targetEntity = Language.class)
    private Language language;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

}