/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.common.Translation;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */
@NoArgsConstructor
@Data
@Entity
@Table(name = "ACTION_BUTTON")
public class ActionButton {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String code;

    /**
     * Position on UI form
     */
    @Basic
    private byte position;

    @OneToMany(targetEntity = Translation.class)
    @JoinColumn(name = "ACTION_BUTTON_CODE")
    private List<Translation> translations;

    public void addTranslation(Translation translation) {
        getTranslations().add(translation);
    }

    public void removeTranslation(Translation translation) {
        getTranslations().remove(translation);
    }

}