/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.common.Translation;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author dmytro
 */
@Entity
@Table(name = "ACTION_BUTTON")
public class ActionButton {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String code;

    /**
     * Position on UI form
     */
    @Basic
    private byte position;

    @OneToMany(targetEntity = Translation.class)
    @JoinColumn(name = "ACTION_BUTTON_CODE")
    private List<Translation> translations;

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public byte getPosition() {
        return this.position;
    }

    public void setPosition(byte position) {
        this.position = position;
    }

    public List<Translation> getTranslations() {
        if (translations == null) {
            translations = new ArrayList<>();
        }
        return this.translations;
    }

    public void setTranslations(List<Translation> translations) {
        this.translations = translations;
    }

    public void addTranslation(Translation translation) {
        getTranslations().add(translation);
    }

    public void removeTranslation(Translation translation) {
        getTranslations().remove(translation);
    }

}