//
// This file was generated by the Jeddict
//
package com.parkhomenko.order;

import java.io.Serializable;
import lombok.ToString;

@ToString
public class ProductInOrderPK implements Serializable {

    private Long shopOrder;

    private Long product;

    public ProductInOrderPK() {
    }

    public ProductInOrderPK(Long shopOrder, Long product) {
        this.shopOrder = shopOrder;
        this.product = product;
    }

    public Long getShopOrder() {
        return this.shopOrder;
    }

    public Long getProduct() {
        return this.product;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final ProductInOrderPK other = (ProductInOrderPK) obj;
        if (!java.util.Objects.equals(this.getShopOrder(), other.getShopOrder())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getProduct(), other.getProduct())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + (this.getShopOrder() != null ? this.getShopOrder().hashCode() : 0);
        hash = 29 * hash + (this.getProduct() != null ? this.getProduct().hashCode() : 0);
        return hash;
    }
}