/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.product.Product;
import com.parkhomenko.common.MonetaryAmount;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Columns;
import org.hibernate.annotations.Type;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "PRODUCT_IN_ORDER")
@IdClass(ProductInOrderPK.class)
public class ProductInOrder {

    @Basic
    private Integer count;

    @Columns(columns = {
        @Column(name = "MONEY_FOR_ONE_GOOD", nullable = false), 
        @Column(name = "CURRENCY_FOR_ONE_GOOD", nullable = false)
    })
    @Type(type = "com.parkhomenko.common.MonetaryAmountCompositeUserType")
    private MonetaryAmount priceForOneGood;

    @Id
    @ManyToOne(targetEntity = Order.class)
    private Order shopOrder;

    @Id
    @ManyToOne(targetEntity = Product.class)
    private Product product;

    @Transient
    private MonetaryAmount totalPrice;
}