/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.product.Product;
import com.parkhomenko.common.MonetaryAmount;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.Columns;
import org.hibernate.annotations.Type;

/**
 * @author dmytro
 */
@Entity
@Table(name = "PRODUCT_IN_ORDER")
@IdClass(ProductInOrderPK.class)
public class ProductInOrder {

    @Basic
    private Integer count;

    @Columns(columns = {
        @Column(name = "MONEY_FOR_ONE_GOOD", nullable = false), 
        @Column(name = "CURRENCY_FOR_ONE_GOOD", nullable = false)
    })
    @Type(type = "com.parkhomenko.common.MonetaryAmountCompositeUserType")
    private MonetaryAmount priceForOneGood;

    @Id
    @ManyToOne(targetEntity = ShopOrder.class)
    private ShopOrder shopOrder;

    @Id
    @ManyToOne(targetEntity = Product.class)
    private Product product;

    @Transient
    private MonetaryAmount totalPrice;

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public MonetaryAmount getPriceForOneGood() {
        return this.priceForOneGood;
    }

    public void setPriceForOneGood(MonetaryAmount priceForOneGood) {
        this.priceForOneGood = priceForOneGood;
    }

    public ShopOrder getShopOrder() {
        return this.shopOrder;
    }

    public void setShopOrder(ShopOrder shopOrder) {
        this.shopOrder = shopOrder;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public MonetaryAmount getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(MonetaryAmount totalPrice) {
        this.totalPrice = totalPrice;
    }

}