/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.order.ProductInOrder;
import com.parkhomenko.order.PaymentSystem;
import com.parkhomenko.customer.Customer;
import com.parkhomenko.common.MonetaryAmount;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Columns;
import org.hibernate.annotations.Type;

/**
 * @author dmytro
 */
@Entity
@Table(name = "SHOP_ORDER")
public class ShopOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private Integer goodsCount;

    @Columns(columns = {
        @Column(name = "money", nullable = false), 
        @Column(name = "currency", nullable = false)
    })
    @Type(type = "com.parkhomenko.common.MonetaryAmountCompositeUserType")
    private MonetaryAmount totalPrice;

    @Column(name = "ORDER_DATE")
    @Basic
    private LocalDateTime date;

    @OneToOne(targetEntity = Customer.class)
    private Customer customer;

    @OneToOne(targetEntity = TransportOrganization.class)
    private TransportOrganization transportOrganization;

    @OneToOne(targetEntity = PaymentSystem.class)
    private PaymentSystem paymentSystem;

    @OneToOne(targetEntity = State.class)
    private State state;

    @OneToMany(targetEntity = ProductInOrder.class, mappedBy = "shopOrder")
    private List<ProductInOrder> products;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getGoodsCount() {
        return this.goodsCount;
    }

    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    public MonetaryAmount getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(MonetaryAmount totalPrice) {
        this.totalPrice = totalPrice;
    }

    public LocalDateTime getDate() {
        return this.date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public TransportOrganization getTransportOrganization() {
        return this.transportOrganization;
    }

    public void setTransportOrganization(TransportOrganization transportOrganization) {
        this.transportOrganization = transportOrganization;
    }

    public PaymentSystem getPaymentSystem() {
        return this.paymentSystem;
    }

    public void setPaymentSystem(PaymentSystem paymentSystem) {
        this.paymentSystem = paymentSystem;
    }

    public State getState() {
        return this.state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public List<ProductInOrder> getProducts() {
        if (products == null) {
            products = new ArrayList<>();
        }
        return this.products;
    }

    public void setProducts(List<ProductInOrder> products) {
        this.products = products;
    }

    public void addProduct(ProductInOrder product) {
        getProducts().add(product);
        product.setShopOrder(this);
    }

    public void removeProduct(ProductInOrder product) {
        getProducts().remove(product);
        product.setShopOrder(null);
    }

}