/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.common.Translation;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author dmytro
 */
@Entity
@Table(name = "STATE_TABLE")
public class State {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @OneToMany(targetEntity = Translation.class)
    @JoinColumn(name = "STATE_ID")
    private List<Translation> translations;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Translation> getTranslations() {
        if (translations == null) {
            translations = new ArrayList<>();
        }
        return this.translations;
    }

    public void setTranslations(List<Translation> translations) {
        this.translations = translations;
    }

    public void addTranslation(Translation translation) {
        getTranslations().add(translation);
    }

    public void removeTranslation(Translation translation) {
        getTranslations().remove(translation);
    }

}