/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.order;

import com.parkhomenko.order.State;
import com.parkhomenko.order.ActionButton;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "WORKFLOW_STATE")
public class WorkflowState {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "WORKFLOW_TYPE")
    @Basic
    private String workflowType;

    @OneToOne(targetEntity = State.class)
    private State state;

    @OneToOne(targetEntity = ActionButton.class)
    @JoinColumn(name = "ACTION_BUTTON_CODE")
    private ActionButton actionButton;

    @OneToMany(targetEntity = WorkflowState.class)
    @JoinColumn(name = "ROOT_STATE_ID")
    private List<WorkflowState> nextStates;

    public void addNextState(WorkflowState nextState) {
        getNextStates().add(nextState);
    }

    public void removeNextState(WorkflowState nextState) {
        getNextStates().remove(nextState);
    }

}