/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.common;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Embeddable
public class GeoCoordinate {

    @Column(nullable = true)
    @Basic
    private long lat;

    @Column(nullable = true)
    @Basic
    private long lng;
}