/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.common;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */
@NoArgsConstructor
@Data
@Entity
@Table(name = "TRANSLATION_TABLE")
public class Translation {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String code;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    private String screen;

    @Column(name = "translation_value", nullable = false)
    @Basic(optional = false)
    @NotNull
    private String value;

    @ManyToOne(targetEntity = Language.class)
    private Language language;
}