/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.common;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author dmytro
 */
@Entity
@Table(name = "TRANSLATION_TABLE")
public class Translation {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String code;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    private String screen;

    @Column(name = "translation_value", nullable = false)
    @Basic(optional = false)
    @NotNull
    private String value;

    @ManyToOne(targetEntity = Language.class)
    private Language language;

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getScreen() {
        return this.screen;
    }

    public void setScreen(String screen) {
        this.screen = screen;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

}