/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.product;

import com.parkhomenko.product.FileType;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.PositiveOrZero;
import javax.validation.constraints.Size;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "ATTACHMENT")
public class Attachment {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false)
    @Lob
    @Basic(fetch = FetchType.EAGER)
    @NotNull
    private byte @NotNull [] file;

    @Column(nullable = false)
    @Basic
    @Enumerated(EnumType.STRING)
    @NotNull
    private FileType type;

    @Column(nullable = false)
    @Basic
    @NotNull
    @Size(min = 1, max = 255)
    private String name;

    @Column(unique = true)
    @Basic
    @PositiveOrZero
    private byte position;
}