/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.product;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
public class Manufacturer {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String internationalName;

    @Basic
    private String shortDescription;

    @Lob
    @Basic
    private byte[] logo;

    @Basic
    private int goodsCount;
}