/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.product;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "PRODUCT_PROPERTY")
public class ProductProperty {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false)
    @Basic
    @NotNull
    private String valueType;

    @Basic
    private String validationRegexp;

    @Basic
    private String validationLengthMin;

    @Basic
    private String validationLengthMax;

    @Basic
    private String name;

    @Basic
    private String shortDescription;

    @OneToMany(targetEntity = PropertyStaticValue.class)
    @JoinColumn(name = "PRODUCT_PROPERTY_ID")
    private List<PropertyStaticValue> property_static_values;

    public void addProperty_static_value(PropertyStaticValue property_static_value) {
        getProperty_static_values().add(property_static_value);
    }

    public void removeProperty_static_value(PropertyStaticValue property_static_value) {
        getProperty_static_values().remove(property_static_value);
    }
}