/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.product;

import com.parkhomenko.product.Product;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * @author dmytro
 */
@Entity
@Table(name = "PRODUCT_EAV")
public class ProductEAV {

    @EmbeddedId
    private ProductEAVPk productEAVEmbeddedId;

    @Column(name = "PROPERTY_VALUE")
    @Basic
    private String value;

    @MapsId("productProperty")
    @ManyToOne(targetEntity = ProductProperty.class)
    @JoinColumn(name = "PRODUCT_PROPERTY_ID")
    private ProductProperty productProperty;

    @MapsId("product")
    @ManyToOne(targetEntity = Product.class)
    private Product product;

    public ProductEAVPk getProductEAVEmbeddedId() {
        return this.productEAVEmbeddedId;
    }

    public void setProductEAVEmbeddedId(ProductEAVPk productEAVEmbeddedId) {
        this.productEAVEmbeddedId = productEAVEmbeddedId;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public ProductProperty getProductProperty() {
        return this.productProperty;
    }

    public void setProductProperty(ProductProperty productProperty) {
        this.productProperty = productProperty;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

}