/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.product;

import com.parkhomenko.product.Product;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "PRODUCT_EAV")
public class ProductEAV {

    @EmbeddedId
    private ProductEAVPk productEAVEmbeddedId;

    @Column(name = "PROPERTY_VALUE")
    @Basic
    private String value;

    @MapsId("productProperty")
    @ManyToOne(targetEntity = ProductProperty.class)
    @JoinColumn(name = "PRODUCT_PROPERTY_ID")
    private ProductProperty productProperty;

    @MapsId("product")
    @ManyToOne(targetEntity = Product.class)
    private Product product;
}