/**
 * This file was generated by the Jeddict
 */
package com.parkhomenko.product;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * It is a dictionary
 *
 * @author dmytro
 */

@NoArgsConstructor
@Data
@Entity
@Table(name = "PROPERTY_STATIC_VALUE")
public class PropertyStaticValue {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "PROPERTY_VALUE")
    @Basic
    private String value;
}